// Generic
export const LOADING = "LOADING";
export const SET_LOADING = "SET_LOADING";
export const LOADING_UNSET = "LOADING_UNSET";
export const CHAT_ERROR = "CHAT_ERROR";

// Site
export const LOAD_APARTMENTS = "LOAD_APARTMENTS";
export const FETCH_APARTMENT = "FETCH_APARTMENT";
export const FETCH_APARTMENT_ERROR = "FETCH_APARTMENT_ERROR";
export const FETCH_APARTMENT_NAME = "FETCH_APARTMENT_NAME";
export const FETCH_APARTMENT_NAME_ERROR = "FETCH_APARTMENT_NAME_ERROR";
export const CREATE_APARTMENT = "CREATE_APARTMENT";
export const CREATE_APARTMENT_ERROR = "CREATE_APARTMENT_ERROR";
export const CLEAR_APARTMENT_SEARCH_RESULTS = "CLEAR_APARTMENT_SEARCH_RESULTS";
export const CREATE_AD_SUCCESS = "CREATE_AD_SUCCESS";
export const CREATE_AD_FAILURE = "CREATE_AD_FAILURE";
export const UPDATE_AD_SUCCESS = "UPDATE_AD_SUCCESS";
export const UPDATE_AD_FAILURE = "UPDATE_AD_FAILURE";
export const FETCH_NBH_AD_SUCCESS = "FETCH_NBH_AD_SUCCESS";
export const FETCH_NBH_AD_FAILURE = "FETCH_NBH_AD_FAILURE";
export const VERIFY_NEIGHBOURHOOD_SUCCESS = "VERIFY_NEIGHBOURHOOD_SUCCESS";
export const VERIFY_NEIGHBOURHOOD_FAILURE = "VERIFY_NEIGHBOURHOOD_FAILURE";
export const DELETE_AD_IMAGE_SUCCESS = "DELETE_AD_IMAGE_SUCCESS";
export const DELETE_AD_IMAGE_FAILURE = "DELETE_AD_IMAGE_FAILURE";
export const CHAT_HISTORY_LOADED = "CHAT_HISTORY_LOADED";
export const REPORTED_AD_SUCCESS = "REPORTED_AD_SUCCESS";
export const REPORTED_AD_FAILURE = "REPORTED_AD_FAILURE";

// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const USER_LOADED = "USER_LOADED";
export const ALT_USER_LOADED = "ALT_USER_LOADED";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const EMAIL_SEND_SUCCESS = "EMAIL_SEND_SUCCESS";
export const EMAIL_SEND_FAILURE = "EMAIL_SEND_FAILURE";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFICATION_FAIL";
export const EMAIL_FOUND = "EMAIL_FOUND";
export const EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND";
export const OTP_GENERATED_SUCCESS = "OTP_GENERATED_SUCCESS";
export const OTP_GENERATED_FAILURE = "OTP_GENERATED_FAILURE";
export const OTP_VALIDATED_SUCCESS = "OTP_VALIDATED_SUCCESS";
export const OTP_VALIDATED_FAILURE = "OTP_VALIDATED_FAILURE";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAILURE = "PASSWORD_CHANGE_FAILURE";
export const EMAIL_VERIFICATION_TIMESTAMP_UPDATED =
  "EMAIL_VERIFICATION_TIMESTAMP_UPDATED";
export const OTP_VERIFICATION_TIMESTAMP_UPDATED =
  "OTP_VERIFICATION_TIMESTAMP_UPDATED";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";
export const DELETE_USER = "DELETE_USER";
export const DELETE_AD = "DELETE_AD";
export const USER_ADS_FETCHED_SUCCESS = "USER_ADS_FETCHED_SUCCESS";
export const USER_ADS_FETCHED_FAILURE = "USER_ADS_FETCHED_FAILURE";
export const LOAD_SELLER_CHATS = "LOAD_SELLER_CHATS";
export const LOAD_BUYER_CHATS = "LOAD_BUYER_CHATS";
export const USER_SUBSCRIPTION_UPDATE_SUCCESS =
  "USER_SUBSCRIPTION_UPDATE_SUCCESS";
export const USER_SUBSCRIPTION_UPDATE_FAILURE =
  "USER_SUBSCRIPTION_UPDATE_FAILURE";
export const MARK_DELETE_SELLER_CHAT = "MARK_DELETE_SELLER_CHAT";
export const MARK_DELETE_BUYER_CHAT = "MARK_DELETE_BUYER_CHAT";
export const UPDATE_NUMBER_SOLD = "UPDATE_NUMBER_SOLD";
export const UPDATE_NUMBER_SOLD_ERROR = "UPDATE_NUMBER_SOLD_ERROR";
export const INVALID_LOGIN_COUNTS = "INVALID_LOGIN_COUNTS";
