// Site
export const FETCH_APARTMENT = "FETCH_APARTMENT";
export const FETCH_APARTMENT_ERROR = "FETCH_APARTMENT_ERROR";
export const CLEAR_APARTMENT_SEARCH_RESULTS = "CLEAR_APARTMENT_SEARCH_RESULTS";
export const LOADING = "LOADING";

// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const EMAIL_SEND_SUCCESS = "EMAIL_SEND_SUCCESS";
export const EMAIL_SEND_FAILURE = "EMAIL_SEND_FAILURE";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFICATION_FAIL";
export const EMAIL_FOUND = "EMAIL_FOUND";
export const EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND";
export const OTP_GENERATED_SUCCESS = "OTP_GENERATED_SUCCESS";
export const OTP_GENERATED_FAILURE = "OTP_GENERATED_FAILURE";
export const OTP_VALIDATED_SUCCESS = "OTP_VALIDATED_SUCCESS";
export const OTP_VALIDATED_FAILURE = "OTP_VALIDATED_FAILURE";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAILURE = "PASSWORD_CHANGE_FAILURE";
export const EMAIL_VERIFICATION_TIMESTAMP_UPDATED =
  "EMAIL_VERIFICATION_TIMESTAMP_UPDATED";
