const buyerGuidelines = [
  "Always check the item thoroughly before making the final payment",
  "If the physical item does not match the description, report the ad so that we may take appropriate action",
  "Make sure to check for any accessories if applicable for an item",
  "If you deem a posted ad to be inappropriate for any reason, report it so that we may review it",
  "Report the seller if you notice multiple violations",
  "Be responsible when reporting an ad. Provide elaborate details about your complaint",
  "For smaller items, try to meet the seller in a common area of your apartment",
  "If you plan to visit the seller's house for a purchase, make sure that you are accompanied by a friend or a family member",
  "While using the private chat feature, make sure to keep the conversation civil and respectful. Report the seller if you find the tone to be inappropriate. Read our chat guidelines for more details",
  "Try to keep your purchases limited to your apartment or neighbourhoods in the immediate vicinity",
];

const sellerGuidelines = [
  "Always post photos along with your ads. They are likely to enhance the possibility of the sale",
  "When selling a used item, be completely transparent about any damages, nicks or scratches. Include supporting photos to enhance your reputation as a seller",
  "Giveaway's imply that you are giving an item away for free. Make sure you select the appropriate option when posting an ad",
  "For items with supporting accessories, make sure you highlight the presence or absence of any and all accessories",
  "Ads automatically expire after 30 days. However, if an item was sold, remember to delete the ad to avoid unnecessary chat messages",
  "For smaller items, try to meet the buyer in a common area of your apartment",
  "When inviting a buyer to your home, make sure there is a friend or a family member present",
  "While using the private chat feature, keep the conversation civil and respectful. Report the buyer by writing to us (contact@nxtdoordeals.com) if you find the tone of the conversation to be inappropriate. Read our chat guidelines for more details",
];

const chatGuidelines = [
  "Keep conversations to the point and related to the ad",
  "If an individual has requested you to stop messaging them, respect his/her choice",
  "Do not indulge in any threatening, intimidating or hurtful behaviour or any action that violates the Terms of Use",
  "If you are at the receiving end of abuse or any inappropriate behaviour, please write to us (contact@nxtdoordeals.com). If reporting a seller, use the Report Ad feature",
];

const bannedItems = [
  "Admissions to educational institutions, political parties and rallies",
  "Adoption of babies and children",
  "Adoption of animals, birds or reptiles of any kind",
  "Adult/sexually oriented/pornographic material or child pornographic material",
  "Advertisements related to promoting a business or products sold as part of the business",
  "Advertisements requesting for services of any kind (example: cooks, domestic help)",
  "Alcohol, e-cigarette and tobacco products",
  "Apartment/property rentals",
  "Astrology services (includes all spiritual/supernatural services)",
  "Burglary tools",
  "Blogs or any discussion or information published on the internet",
  "Chemicals of all kinds (includes radioactive materials)",
  "Child labour or slavery (includes all services which fall within the ambit of child welfare laws of India)",
  "Contraband items",
  "Crypto-currency",
  "Currency (includes notes and coins considered as legal tender - Indian or otherwise)",
  "Dating and escort services",
  "Discrimination based on race, caste, gender, religion and region by mention in ads",
  "Education certificates and diplomas",
  "Election (government or private) related ads",
  "Ethnically or racially offensive material",
  "Food (cooked or uncooked)",
  "Firecrackers and explosives",
  "Foreign exchange (includes collecting and remitting payments in person or via remittance portals)",
  "Gas cylinders and related products without the approval and registration of government agencies",
  "Government-issued id's (includes services like document collection for id creation)",
  "Job advertisements of all kinds (public, private or otherwise)",
  "Hellevator schemes",
  "Human blood, bodily fluids and human parts",
  "Hacking - devices that circumvent or infringe IP laws (example: devices to unlock phones)",
  "IPR media violation - selling pirated copies of music, movies or other media protected by a license",
  "IPR software violation - selling pirated copies of software or video games protected by a license",
  "Ivory products",
  "Loans of all kinds",
  "Lottery tickets",
  "Medical equipment requiring licenses (example: X-ray machines, scanners)",
  "Police, army, navy and airforce related items",
  "Political propaganda",
  "Property for sale",
  "Stocks, shares and other securities",
  "Surrogacy",
  "Tickets, vouchers and passes for events of all kinds (example: sports, music, theatre)",
  "Transfer of memberships, subscriptions, certificates and timeshares",
  "Used cosmetics, undergarments, personal hygiene & grooming items (example: epilators, shavers)",
  "Weapons (including but not limited to guns, swords, knives)",
];

export { buyerGuidelines, sellerGuidelines, chatGuidelines, bannedItems };
